RecipeViewerEvents.removeEntries('item', event => {
	event.remove('mekanism:digital_miner');
	event.remove('railcraft:blast_furnace_bricks');
	event.remove('relics:infinity_ham');
	event.remove('artifacts:everlasting_beef');
	event.remove('artifacts:eternal_steak');
	event.remove('refurbished_furniture:post_box');
	event.remove('refurbished_furniture:oak_mail_box');
	event.remove('refurbished_furniture:spruce_mail_box');
	event.remove('refurbished_furniture:birch_mail_box');
	event.remove('refurbished_furniture:jungle_mail_box');
	event.remove('refurbished_furniture:acacia_mail_box');
	event.remove('refurbished_furniture:dark_oak_mail_box');
	event.remove('refurbished_furniture:mangrove_mail_box');
	event.remove('refurbished_furniture:cherry_mail_box');
	event.remove('refurbished_furniture:crimson_mail_box');
	event.remove('refurbished_furniture:warped_mail_box');
	event.remove('mekanism:portable_teleporter');
	event.remove('mekanism:teleporter');
	event.remove('mekanism:teleporter_frame');
})