#Charge Abilities
#Enables the ability to charge up the Sledgehammer by using it.
#When releasing can excavate, vein mine ores, and fell trees.
chargeAbilities = true
#Excavate Ability
#Enables the ability to excavate using a Sledgehammer.
#This ability destroys a 3x3 flat cube (by default) of blocks.
excavateAbility = true
#Vein Mine Ability
#Enables the ability to vein mine ores using a Sledgehammer.
#This ability destroys all connected ores.
veinMineAbility = true
#Fell Tree Ability
#Enables the ability to fell trees using a Sledgehammer.
#This ability destroys all connected logs.
fellTreeAbility = true
#Max Vein Mine Size
#The maximum amount of blocks that a Sledgehammer can break at once using the charge ability.
# Default: 64
# Range: 0 ~ 1024
maxVeinMineSize = 64
#Starlight Upgrade Spawn Chance
#The chance of a Starlight Upgrade Smithing Template appearing in an ancient city or end city chest.
#Set it to 0 to prevent spawning. Set it to 1 to guarantee spawning.
# Default: 0.2
# Range: 0.0 ~ 1.0
starlightUpgradeSpawnChance = 0.2
#Starlight Upgrade Spawn Amount
#The amount of Starlight Upgrade Smithing Templates appear in a chest.
# Default: 2
# Range: 1 ~ 64
starlightUpgradeSpawnAmount = 2
